CREATE TABLE tb_order
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moment     TIMESTAMP WITH TIME ZONE NOT NULL,
    status     VARCHAR(20)              NOT NULL,
    client_id  BIGINT                   NOT NULL,
    payment_id BIGINT                   NOT NULL
);

CREATE TABLE tb_order_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity   INTEGER        NOT NULL,
    price      DECIMAL(10, 2) NOT NULL,
    product_id BIGINT,
    order_id   BIGINT         NOT NULL,
    CONSTRAINT fk_order_order_item
        FOREIGN KEY (order_id)
            REFERENCES tb_order (id)
);